parameters:
#    integral_core.example.class: Integral\CoreBundle\Example

services:
#    integral_core.example:
#        class: %integral_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
